import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import Nav from "@/components/Nav";
import Link from "next/link";
import { useEffect, useState } from "react";
import VideoPlayer from "@/components/VideoPlayer";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const [mouseX, setMouseX] = useState(-10);
  const [mouseY, setMouseY] = useState(-10);
  const [enlarged, setEnlarged] = useState(false);
  const [opac, setOpac] = useState(0);
  useEffect(() => {
    const mouse = document.querySelector(".mouse");
    addEventListener("mousemove", (event) => {
      setMouseX(event.clientX);
      setMouseY(event.clientY);

      const result = getComputedStyle(event.target).getPropertyValue("cursor");
      if (result == "pointer") {
        mouse.style.height = "20px";
        mouse.style.width = "20px";
        setEnlarged(true);
      } else {
        mouse.style.height = "10px";
        mouse.style.width = "10px";
        setEnlarged(false);
      }
    });
    const title = document.querySelector(" .title");
    const text = document.querySelector(" .text");
    const cont = document.querySelector(" .containment");
    const copyright = document.querySelector(" .copyright");
    const wall = document.querySelector(".wall");
    title.style.position = "relative";
    text.style.opacity = "0";
    cont.style.left = "50%";
    cont.style.top = "50%";
    cont.style.transform = "translate(-50%, -30%)";
    cont.style.overflow = "hidden";
    setTimeout(() => {
      title.style.transform = "translate(0, 0)";
    }, 500);
    setTimeout(() => {
      title.style.position = "relative";
      cont.style.transform = "translate(0, 0)";
      cont.style.top = "0";
      cont.style.left = "0";
    }, 1000);
    setTimeout(() => {
      cont.style.overflow = "visible";
      text.style.opacity = "1";
      copyright.style.transform = "translate(0, 0)";
      wall.style.opacity = "0";
      wall.style.visibility = "none";
      setOpac(1);
    }, 1500);
  }, []);
  return (
    <>
      <Head>
        <title>Woxels</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="relative text-[#030303] bg-[#FCFCFC] h-screen w-screen overflow-hidden">
        <div
          style={{
            transform: `translate3d(${
              (enlarged && mouseX - 10) || mouseX - 5
            }px, ${(enlarged && mouseY - 10) || mouseY - 5}px, 0)`,
            pointerEvents: "none",
            userSelect: "none",
            mixBlendMode: "difference",
            zIndex: "100000000",
          }}
          className={`mouse h-[10px] w-[10px] bg-[#FCFCFC] rounded-full duration-[50ms] absolute`}
        />
        <Nav Home={true} opacity={opac} />
        <div className="ml-[20px] absolute top-[50%] left-[50%] mt-[20px] w-min z-[1000000] containment duration-500">
          <h1
            className="absolute translate-y-[-100%] 4k:text-[480px] 2k:text-[420px] hd:text-[360px] 2xl:text-[320px] xl:text-[280px] lg:text-[230px] md:text-[160px] sm:text-[120px] text-[60px] uppercase title mb-[-20px] z-[10] duration-500"
            style={{ pointerEvents: "none", userSelect: "none" }}
          >
            Woxels
          </h1>
          <div className="opacity-0 lg:translate-y-[-60px] translate-y-[30px] z-10 text duration-500">
            <p className="2xl:text-[24px] xl:text-[20px] lg:text-[18px] md:text-[14px] text-[10px] italic text-center">
              Website Design. Creative Design. Immersive Design. Quality Design.
            </p>
            <p className="2xl:text-[24px] xl:text-[20px] lg:text-[18px] md:text-[14px] text-[10px] max-w-[628px] mx-auto mt-[20px]">
              Our goal is to help your business grow and maximize its potential
              by reaching customers and clients online in an age of technology
              and social media. With our help, you will be able to take things
              to the next level and help more people.
            </p>
            <div className="flex items-center justify-center z-[100]">
              <Link href="/contact" className="group h-[0px]">
                <p className="bg-[#030303] text-[#FCFCFC] p-5 2xl:text-[24px] xl:text-[20px] lg:text-[18px] md:text-[14px] sm:text-[8px] text-[6px] mt-[20px] z-[100] border-2 border-[#030303] group-hover:bg-[#FCFCFC] group-hover:text-[#030303] duration-[200ms]">
                  Contact Us
                </p>
              </Link>
            </div>
          </div>
        </div>
        <div className="absolute w-[45vw] overflow-hidden hd:right-[20px] hd:bottom-[20px] right-[20px] bottom-[20px] top-[0px] z-0">
          <VideoPlayer />
        </div>
        <div className="absolute overflow-hidden bottom-0 left-0 ml-[20px] mb-[20px] md:text-[14px] text-[10px] z-[100001]">
          <p className="translate-y-[100%] duration-500 copyright z-[100001]">
            &copy; Woxels 2023
          </p>
        </div>
      </main>
      <div className="wall w-screen absolute h-screen top-0 left-0 z-[100000] bg-[#FCFCFC] duration-500"></div>
    </>
  );
}
